apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-front
  labels:
    app: node-front
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node-front
  template:
    metadata:
      labels:
        app: node-front
    spec:
      containers:
      - name: node-front
        image: us-central1-docker.pkg.dev/tss-2s2024/docker-ulink/node-front:v6
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: 64Mi
            cpu: 50m
          limits:
            memory: 128Mi
            cpu: 100m