name: 'Build and Deploy to GKE Test'

on:
  push:
    branches: 
      - main

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  GKE_CLUSTER: autopilot-cluster-ulink
  GKE_ZONE: us-central1
  NOMBRE_IMAGEN: us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/docker-ulink/${{ github.event.repository.name }}:${{ github.sha }}

jobs:
  build_publish_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: prueba de archivos
        run: ls -al
