name: 'Build and Deploy to GKE'

on:
  push:
    branches: 
      - '"main"'

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  GKE_CLUSTER: autopilot-cluster-ulink
  GKE_ZONE: us-central1
  # IMAGE: 

jobs:
  hello_world:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup gcloud CLI
        uses: google-github-actions/setup-gcloud@v1
        with:
          service_account_key: ${{ secrets.GKE_SA_KEY }}
          project_id: ${{ secrets.GKE_PROJECT }}

      - name: Configurar Docker para Autenticación
        run: gcloud --quiet auth configure-docker

      - name: Obtener credenciales de GKE para deployar al cluster
        uses: google-github-actions/get-gke-credentials@db150f2cc60d1716e61922b832eae71d2a45938f
        with:
          cluster_name: ${{ env.GKE_CLUSTER }}
          location: ${{ env.GKE_ZONE }}
          credentials: ${{ secrets.GKE_SA_KEY }}

      - name: Prueba del Kubernetes
        run: kubectl get all
